dist: xenial
language: python
python: 3.8.1

install:
- make bootstrap

script:
- make lint
- make test

after_script:
- make cover
- sonar-scanner
- codecov --token=${codecov_token}

addons:
  sonarcloud:
    organization: "xfrnk2-github"
    token: ${sonarcloud_token}